"""Improve OCRResult model

Revision ID: 6f9fefbb4efd
Revises: 32a6e546965b
Create Date: 2026-07-14 00:17:31.747903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9fefbb4efd'
down_revision: Union[str, Sequence[str], None] = '32a6e546965b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_results', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('ocr_results', sa.Column('processing_time', sa.Float(), nullable=False))
    op.add_column('ocr_results', sa.Column('page_count', sa.Integer(), nullable=False))
    op.add_column('ocr_results', sa.Column('engine_version', sa.String(length=50), nullable=False))
    op.add_column('ocr_results', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'ocr_results', ['document_id'])
    op.drop_column('ocr_results', 'extracted_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_results', sa.Column('extracted_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ocr_results', type_='unique')
    op.drop_column('ocr_results', 'created_at')
    op.drop_column('ocr_results', 'engine_version')
    op.drop_column('ocr_results', 'page_count')
    op.drop_column('ocr_results', 'processing_time')
    op.drop_column('ocr_results', 'text')
    # ### end Alembic commands ###
